import {
  Activity,
  Bell,
  Bot,
  Braces,
  Brain,
  Building2,
  CalendarClock,
  ClipboardList,
  Clock,
  CreditCard,
  Ellipsis,
  FileJson,
  FileText,
  Filter,
  GitBranch,
  Globe,
  Handshake,
  Hash,
  Inbox,
  ListChecks,
  Mail,
  MessageSquare,
  Merge,
  MousePointerClick,
  Network,
  Notebook,
  PenLine,
  ScanLine,
  ScrollText,
  Send,
  Sheet,
  ShoppingCart,
  Shuffle,
  Sparkles,
  Split,
  SquareCode,
  SquareStack,
  StickyNote,
  Table2,
  Tags,
  Timer,
  UserPlus,
  Variable,
  Webhook,
  Zap,
  type LucideIcon,
} from 'lucide-react'

/**
 * Icons referenced by data (node definitions, integrations, templates) are
 * resolved through this map so the dataset stays serialisable — a real API
 * would hand us the same strings.
 */
const ICONS: Record<string, LucideIcon> = {
  activity: Activity,
  bell: Bell,
  bot: Bot,
  braces: Braces,
  brain: Brain,
  building: Building2,
  calendar: CalendarClock,
  clipboard: ClipboardList,
  clock: Clock,
  code: SquareCode,
  creditCard: CreditCard,
  ellipsis: Ellipsis,
  fileJson: FileJson,
  fileText: FileText,
  filter: Filter,
  gitBranch: GitBranch,
  globe: Globe,
  handshake: Handshake,
  hash: Hash,
  inbox: Inbox,
  listChecks: ListChecks,
  mail: Mail,
  merge: Merge,
  messageSquare: MessageSquare,
  mouse: MousePointerClick,
  network: Network,
  notebook: Notebook,
  penLine: PenLine,
  scan: ScanLine,
  scroll: ScrollText,
  send: Send,
  sheet: Sheet,
  shoppingCart: ShoppingCart,
  shuffle: Shuffle,
  sparkles: Sparkles,
  split: Split,
  stack: SquareStack,
  stickyNote: StickyNote,
  table: Table2,
  tags: Tags,
  timer: Timer,
  userPlus: UserPlus,
  variable: Variable,
  webhook: Webhook,
  zap: Zap,
}

export function resolveIcon(name: string | undefined): LucideIcon {
  return (name && ICONS[name]) || Zap
}
